version: "3"
services:
 vampi-vulnerable:
  build: ./
  container_name: vampi-vulnerable
  ports:
   - 5002:5000
  environment:
   - vulnerable=1
   - tokentimetolive=60
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:5000"]
    interval: 10s
    timeout: 5s
    retries: 5
