version: "3"
services:
 vampi-secure:
  build: ./
  container_name: vampi-secure
  ports:
   - 5000:5000
  environment:
   - vulnerable=1

 #vampi-vulnerable:
 # build: ./
 # container_name: vampi-vulnerable
 # ports:
 #  - 5002:5000
 # environment:
 #  - vulnerable=1
