name: Bright

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: USERNAME
          password: ${{ secrets.DOCKERHUB_BRIGHT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: brightsec/vampi:latest
          platforms: linux/amd64,linux/arm64

      - name: Start application
        run: |
          docker compose up --wait &
        env:
          tokentimetolive: 60
          vulnerable: 1

      - name: Probe application readiness
        run: |
          for i in {1..30}; do curl -sS -o /dev/null http://127.0.0.1:5002 && exit 0 || sleep 5; done; exit 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install SecTesterJS dependencies
        run: |
          npm i --save=false --prefix .brightsec @sectester/core@0.49.0 @sectester/repeater@0.49.0 @sectester/scan@0.49.0 @sectester/runner@0.49.0 @sectester/reporter@0.49.0

      - name: Authenticate with Bright
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: app.brightsec.com
          BRIGHT_PROJECT_ID: test-copilot-authid-debug
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Run security tests
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning --test-force-exit --test-concurrency=4 --test .brightsec/tests/*.test.ts
        env:
          BRIGHT_HOSTNAME: app.brightsec.com
          BRIGHT_PROJECT_ID: test-copilot-authid-debug
          BRIGHT_AUTH_ID: ${{ vars.BRIGHT_AUTH_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TOKEN: ${{ env.BRIGHT_TOKEN }}
          BRIGHT_TARGET_URL: http://127.0.0.1:5002
          SECTESTER_SCAN_POOL_SIZE: ${{ vars.SECTESTER_SCAN_POOL_SIZE }}